$utf8 = New-Object System.Text.UTF8Encoding($false)

$cn = [System.IO.File]::ReadAllText('README.md', $utf8)
$cn = $cn.Replace('<strong><a href="https://www.cac.gov.cn/2023-07/13/c_1690898326795531.htm">《生成式人工智能服务管理暂行办法》发布</a></strong><br/>' + "`r`n" + '        国家层面为生成式 AI 服务建立基础治理框架，明确“发展与安全并重”的总方向。', '<strong><a href="https://www.cac.gov.cn/2023-07/13/c_1690898327029107.htm">《生成式人工智能服务管理暂行办法》</a></strong><br/>' + "`r`n" + '        第十条明确要求提供者采取有效措施，防范未成年人用户过度依赖或者沉迷生成式人工智能服务。')
$cn = $cn.Replace('<strong><a href="https://www.cac.gov.cn/2026-01/23/c_1770728780862340.htm">八部门发布《可能影响未成年人身心健康的网络信息分类办法》</a></strong><br/>' + "`r`n" + '        对可能影响未成年人身心健康的信息进行细化分类，并把算法推荐、生成式人工智能等新技术带来的内容风险纳入治理视野。', '<strong><a href="https://www.cac.gov.cn/2026-01/23/c_1770728781060093.htm">《可能影响未成年人身心健康的网络信息分类办法》</a></strong><br/>' + "`r`n" + '        第九条明确要求：提供算法推荐、生成式人工智能等服务的，不得向未成年人推送可能影响其身心健康的网络信息。')
[System.IO.File]::WriteAllText('README.md', $cn, $utf8)

$en = [System.IO.File]::ReadAllText('README_EN.md', $utf8)
$en = $en.Replace('<strong><a href="https://www.cac.gov.cn/2023-07/13/c_1690898326795531.htm">Release of the <em>Interim Measures for the Administration of Generative AI Services</em></a></strong><br/>' + "`r`n" + '        China established a baseline governance framework for generative AI services and made “development and safety in parallel” an explicit top-level principle.', '<strong><a href="https://www.cac.gov.cn/2023-07/13/c_1690898327029107.htm"><em>Interim Measures for the Administration of Generative AI Services</em></a></strong><br/>' + "`r`n" + '        Article 10 requires providers to take effective measures to prevent minors from becoming overly dependent on or addicted to generative AI services.')
$en = $en.Replace('<strong><a href="https://www.cac.gov.cn/2026-01/23/c_1770728780862340.htm">Eight agencies released the <em>Measures for Classifying Online Information that May Affect the Physical and Mental Health of Minors</em></a></strong><br/>' + "`r`n" + '        The rule refined the categories of harmful or risky information for minors and explicitly brought algorithmic recommendation and generative AI risks into the governance scope.', '<strong><a href="https://www.cac.gov.cn/2026-01/23/c_1770728781060093.htm"><em>Measures for Classifying Online Information that May Affect the Physical and Mental Health of Minors</em></a></strong><br/>' + "`r`n" + '        Article 9 makes clear that algorithmic recommendation and generative AI services must not push harmful-or-risky information to minors.')
[System.IO.File]::WriteAllText('README_EN.md', $en, $utf8)
